# Generated by Django 3.0.4 on 2020-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstPage', '0004_auto_20200423_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
