# Generated by Django 3.0.4 on 2020-05-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstPage', '0006_auto_20200506_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='photo3',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/attachments')),
                ('id_Attraction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FirstPage.Attractions')),
            ],
        ),
    ]
